#!/usr/bin/env bash
#
# Installs ProtoMap self-hosted: generates the configuration with secrets and a setup key, pulls the image from Docker
# Hub, and starts it. The configuration goes to .env next to compose.yaml, or to the file named by --env-file, which
# every later docker compose command then needs too.
#
# Usage: ./install.sh [--env-file PATH]

set -euo pipefail

env_temp=""
cleanup() {
    if [ -n "$env_temp" ]; then
        rm -f "$env_temp"
    fi
}
trap cleanup EXIT

say() { printf '%s\n' "$*"; }
heading() { printf '\n%s\n' "$*"; }
fail() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

# Prints $1 random bytes, base64url-encoded without padding or newlines.
generate_secret() {
    if command -v openssl > /dev/null 2>&1; then
        openssl rand -base64 "$1" | tr -d '\n=' | tr '+/' '-_'
    else
        head -c "$1" /dev/urandom | base64 | tr -d '\n=' | tr '+/' '-_'
    fi
}

env_file=""
case "${1:-}" in
    "") ;;
    --env-file)
        [ "$#" -eq 2 ] && [ -n "$2" ] || fail "Usage: ./install.sh [--env-file PATH]"
        env_file="$2"
        ;;
    *) fail "Usage: ./install.sh [--env-file PATH]" ;;
esac
# A relative path starts from where the installer was run, not from its own folder.
case "$env_file" in
    "" | /*) ;;
    *) env_file="$PWD/$env_file" ;;
esac
cd "$(dirname "$0")"
env_file="${env_file:-$PWD/.env}"
env_label=".env"
compose_command="docker compose"
if [ "$env_file" != "$PWD/.env" ]; then
    env_label="$env_file"
    compose_command="docker compose --env-file $env_file"
fi

heading "CHECK REQUIREMENTS"
command -v docker > /dev/null 2>&1 || fail "Docker is required. Install it first: https://docs.docker.com/get-docker/"
docker compose version > /dev/null 2>&1 || fail "Docker Compose v2 is required. Update Docker or install the plugin."
if [ -e "$env_file" ] || [ -L "$env_file" ]; then
    fail "ProtoMap is already installed here. Delete ${env_label} to install again."
fi
[ -d "$(dirname "$env_file")" ] || fail "The folder of ${env_label} does not exist."

heading "SELECT INSTALLATION"
say "1) Trial: uses the bundled PostgreSQL."
say "2) Production: uses your PostgreSQL 18 or newer."
while :; do
    read -r -p "Select 1 or 2 [default: 1]: " install_type
    install_type="${install_type:-1}"
    case "$install_type" in
        1 | 2) break ;;
        *) say "Enter 1 or 2." ;;
    esac
done
while :; do
    read -r -p "Port [default: 3300]: " port
    port="${port:-3300}"
    case "$port" in
        *[!0-9]* | "") say "Enter a port from 1 to 65535." ;;
        *)
            if [ "$port" -ge 1 ] && [ "$port" -le 65535 ]; then
                break
            fi
            say "Enter a port from 1 to 65535."
            ;;
    esac
done
database_url=""
if [ "$install_type" = "2" ]; then
    say "Enter your PostgreSQL URL in the form postgres://USER:PASSWORD@HOST:PORT/DATABASE"
    while :; do
        read -r -s -p "PostgreSQL URL: " database_url
        say ""
        case "$database_url" in
            *"'"*) say "Percent-encode single quotes in the URL." ;;
            postgres://* | postgresql://*) break ;;
            *) say "Enter a URL that starts with postgres:// or postgresql://." ;;
        esac
    done
fi

heading "GENERATE SECRETS"
setup_key="$(generate_secret 32)"
admin_password="$(generate_secret 32)"
secret_key="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
umask 077
env_temp="$(mktemp "$(dirname "$env_file")/.env.tmp.XXXXXX")"
{
    printf '# Generated by install.sh. Keep this file private: it contains secrets.\n\n'
    printf 'PROTOMAP_SETUP_KEY=%s\n' "$setup_key"
    printf 'PROTOMAP_ADMIN_PASSWORD=%s\n' "$admin_password"
    printf 'PROTOMAP_SECRET_KEY=%s\n' "$secret_key"
    printf 'PROTOMAP_PORT=%s\n\n' "$port"
    if [ "$install_type" = "1" ]; then
        printf 'COMPOSE_PROFILES=postgres\n'
        printf 'POSTGRES_USER=protomap\n'
        printf 'POSTGRES_PASSWORD=%s\n' "$(generate_secret 32)"
        printf 'POSTGRES_DB=protomap\n'
        # Compose expands these references when it reads the file.
        # shellcheck disable=SC2016
        printf 'PROTOMAP_DATABASE_URL=%s\n' 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}'
    else
        printf "PROTOMAP_DATABASE_URL='%s'\n" "$database_url"
    fi
} > "$env_temp"
mv "$env_temp" "$env_file"
env_temp=""

url="http://localhost:${port}"
heading "SETUP KEY"
say "Open ${url} and create the owner's account with this setup key, which is also in ${env_label}:"
say "  ${setup_key}"

heading "START"
say "Pulling the image and starting the services."
if ! docker compose --env-file "$env_file" up --detach --wait; then
    fail "The services did not start. Fix the reported error and run: ${compose_command} up --detach --wait"
fi

heading "DONE"
say "ProtoMap is running at ${url}."
say ""
say "Members scan repositories with the ProtoMap CLI on their computers: they install it as ${url} shows, log in"
say "with \"protomap login --server=${url}\", and run \"protomap scan\" in their repositories. Continuous"
say "integration scans with an organization API key, which admins create in the platform's settings:"
say "  export PROTOMAP_URL=${url} PROTOMAP_API_KEY=<API key>"
say "  protomap scan /path/to/repository"
say ""
say "The job queue dashboard is at http://127.0.0.1:8801 on this computer only, with the user admin and"
say "PROTOMAP_ADMIN_PASSWORD from ${env_label}. To open it from another computer, forward its port there first:"
say "  ssh -L 8801:127.0.0.1:8801 <this computer>"
